### ISSUE TITLE
sql导入报错

### ISSUE THREAD

**Issue by D4rkspider** [xiaoxiaoranxxx/POT-ZHIYUN#2]
换了好几个版本的mysql都导入报错

导入数据库失败!
D ERROR 1064 14200 at ine 308:You have an erorin your OL syntax;checkthe manual that coresponds to your MysOL serer version for the ioht syntax to us nar "INSERT INTC
cms sysinfo`VALUES (5,'2024-08-09 19:18:59', 'mailhost', 'smtp.16' at line 2

**Comment by xiaoxiaoranxxx** [comment]
要用8版本的，可以用docker正常启动吗？












肖萧然
***@***.***

肖萧然如冯虚御风而不知其所止，飘飘然如遗世独立，羽化而登仙。




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月27日(周五) 下午5:39
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [xiaoxiaoranxxx/POT-ZHIYUN] sql导入报错 (Issue #2)




 
换了好几个版本的mysql都导入报错
 
导入数据库失败!
 D ERROR 1064 14200 at ine 308:You have an erorin your OL syntax;checkthe manual that coresponds to your MysOL serer version for the ioht syntax to us nar "INSERT INTC
 cms sysinfo`VALUES (5,'2024-08-09 19:18:59', 'mailhost', 'smtp.16' at line 2

**Comment by D4rkspider** [comment]
用的是8.0的，宝塔上默认给我装的是8.0.36的，我用phpstudy上的8.0.12的也不行

**Comment by D4rkspider** [comment]
折腾了好久都没有搞定，还望大佬指点

**Comment by xiaoxiaoranxxx** [comment]
晚点我看看，docker直接启动应该没问题吧












肖萧然
***@***.***

肖萧然如冯虚御风而不知其所止，飘飘然如遗世独立，羽化而登仙。




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月27日(周五) 下午5:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaoxiaoranxxx/POT-ZHIYUN] sql导入报错 (Issue #2)




 
折腾了好久都没有搞定，还望大佬指点

**Comment by D4rkspider** [comment]
一开始没打算用docker，刚刚试了一下，拉取mysql镜像超时
root@hcss-ecs-bfb2:~/POT-ZHIYUN# docker-compose up -d
Pulling mysql (mysql:8.0.22)...
ERROR: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by D4rkspider** [comment]
我换个源先

**Comment by D4rkspider** [comment]
师傅能请教一下换什么源可以解决docker-compose的问题吗？拉不下来镜像

**Comment by xiaoxiaoranxxx** [comment]
> 要用8版本的，可以用docker正常启动吗？ 肖萧然 ***@***.*** 肖萧然如冯虚御风而不知其所止，飘飘然如遗世独立，羽化而登仙。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年12月27日(周五) 下午5:39 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [xiaoxiaoranxxx/POT-ZHIYUN] sql导入报错 (Issue #2) 换了好几个版本的mysql都导入报错 导入数据库失败! D ERROR 1064 14200 at ine 308:You have an erorin your OL syntax;checkthe manual that coresponds to your MysOL serer version for the ioht syntax to us nar "INSERT INTC cms sysinfo`VALUES (5,'2024-08-09 19:18:59', 'mailhost', 'smtp.16' at line 2 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

我看了下,那个sql语句那里没有加 ; 号导致插入报错,目前我已经加上了,应该没有问题了🫡🫡🫡🫡

**Comment by xiaoxiaoranxxx** [comment]
> 一开始没打算用docker，刚刚试了一下，拉取mysql镜像超时 root@hcss-ecs-bfb2:~/POT-ZHIYUN# docker-compose up -d Pulling mysql (mysql:8.0.22)... ERROR: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

这个可以改成这个

/etc/docker/daemon.json

```
{
  "registry-mirrors": ["https://docker.adysec.com"]
}
```

**Comment by D4rkspider** [comment]
谢谢您，我这边本地搞定了，docker的话用这个源还是容易下到一半就超时/(ㄒoㄒ)/~~

**Comment by xiaoxiaoranxxx** [comment]
> 谢谢您，我这边本地搞定了，docker的话用这个源还是容易下到一半就超时/(ㄒoㄒ)/~~

没事没事,又什么问题建议多反馈🦄🦄🦄
